19-Django_Level_Four/learning_templates/basic_app/urls.py
from django.urls import path
from basic_app import views

# TEMPLATE TAGGING
app_name = 'basic_app'

urlpatterns= [
    path('relative/', views.relative, name='relative'),
    path('other/', views.other, name='other'),
]

19-Django_Level_Four/learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls')),
]

19-Django_Level_Four/learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'hello world', 'number':100}
    return render(request, 'basic_app/index.html', context_dict)

def other(request):
    return render(request, 'basic_app/other.html')

def relative(request):
    return render(request, 'basic_app/relative_url_templates.html')

19-Django_Level_Four/learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <ul class="navbar-nav mr-auto">
                <li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
                <li><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class="nav-link" href="{% url 'basic_app:other' %}">Other</a></li>
            </ul>

        </div>
    </nav>

    <div class="container">

        {% block body_block %}
        <!-- Anything outside of this will be inherited if you extend!  -->
        {% endblock %}

    </div>
    
</body>
</html>

19-Django_Level_Four/learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
    {% block body_block %}
        <h1>WELCOME TO INDEX</h1>
        <!-- <h2>This is index.html page showing!</h2> -->
        <h1>{{ text|cut:'world' }}</h1>
        <h1>{{ number|add:"99" }}</h1>
    {% endblock %}

19-Django_Level_Four/learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
    {% block body_block %}

        <h1>WELCOME TO OTHER</h1>
        <h2>This is an example of template inheritance!</h2>
    {% endblock %}

19-Django_Level_Four/learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
</head>
<body>
    <h1>WELCOME TO RELATIVE URL TEMPLATES</h1>

    <!-- 'basic_app' needs to match from urls.py app_name in basic_app -->
    <a href="{% url 'basic_app:other' %}">THE OTHER PAGE</a>
    <a href="{% url 'admin:index' %}">LINK TO ADMIN</a>
    <a href="{% url 'index' %}">LINK TO INDEX</a>

</body>
</html>